In [4]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.matmul(a, b)
print(c)


d = np.array([[1, 2, 3],
              [4, 5, 6]])
e = np.array([[7, 8],
              [9, 10],
              [11, 12]])
f = np.matmul(d, e)
print(f)

g = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
h = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
i = np.matmul(g, h)
print(i)

[[19 22]
 [43 50]]
[[ 58  64]
 [139 154]]
[[ 50  60]
 [114 140]]
